sudo: required
language: nodejs
node_js:
  "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - "node_modules"
before_install:
  - npm install
script:
  npm test
