sudo: required
language: nodejs
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_install:
  - npm install
script:
  npm test
